# Concrete quality analysis (Linear Regression)

### Importing modules

In [271]:
import numpy as np

from sklearn.model_selection import cross_val_score, KFold, train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, max_error

from pandas import read_excel

### Read file and convert as float array

In [272]:
df = read_excel("./Concrete_Data.xls",sheet_name="Sheet1",header=0,nrows=1030,dtype=float)
df

Cement (component 1)(kg in a m^3 mixture)   
0                                         540.0  \
1                                         540.0   
2                                         332.5   
3                                         332.5   
4                                         198.6   
...                                         ...   
1025                                      276.4   
1026                                      322.2   
1027                                      148.5   
1028                                      159.1   
1029                                      260.9   

      Blast Furnace Slag (component 2)(kg in a m^3 mixture)   
0                                                   0.0      \
1                                                   0.0       
2                                                 142.5       
3                                                 142.5       
4                                                 132.4       
...                                                 ...       
1025                                              116.0       
1026                                                0.0       
1027                                              139.4       
1028                                              186.7       
1029                                              100.5       

      Fly Ash (component 3)(kg in a m^3 mixture)   
0                                            0.0  \
1                                            0.0   
2                                            0.0   
3                                            0.0   
4                                            0.0   
...                                          ...   
1025                                        90.3   
1026                                       115.6   
1027                                       108.6   
1028                                         0.0   
1029                                        78.3   

      Water  (component 4)(kg in a m^3 mixture)   
0                                         162.0  \
1                                         162.0   
2                                         228.0   
3                                         228.0   
4                                         192.0   
...                                         ...   
1025                                      179.6   
1026                                      196.0   
1027                                      192.7   
1028                                      175.6   
1029                                      200.6   

      Superplasticizer (component 5)(kg in a m^3 mixture)   
0                                                   2.5    \
1                                                   2.5     
2                                                   0.0     
3                                                   0.0     
4                                                   0.0     
...                                                 ...     
1025                                                8.9     
1026                                               10.4     
1027                                                6.1     
1028                                               11.3     
1029                                                8.6     

      Coarse Aggregate  (component 6)(kg in a m^3 mixture)   
0                                                1040.0     \
1                                                1055.0      
2                                                 932.0      
3                                                 932.0      
4                                                 978.4      
...                                                 ...      
1025                                              870.1      
1026                                              817.9      
1027                                              892.4      
1028                                         

In [273]:
concrete_arr = df.to_numpy(float)
concrete_arr

array([[540.        ,   0.        ,   0.        , ..., 676.        ,
         28.        ,  79.98611076],
       [540.        ,   0.        ,   0.        , ..., 676.        ,
         28.        ,  61.88736576],
       [332.5       , 142.5       ,   0.        , ..., 594.        ,
        270.        ,  40.26953526],
       ...,
       [148.5       , 139.4       , 108.6       , ..., 780.        ,
         28.        ,  23.69660064],
       [159.1       , 186.7       ,   0.        , ..., 788.9       ,
         28.        ,  32.76803638],
       [260.9       , 100.5       ,  78.3       , ..., 761.5       ,
         28.        ,  32.40123514]])

### Split array in features and results:

In [ ]:
X = concrete_arr[:,:-1]
y = concrete_arr[:,-1]
X.shape

### Split x and y into X_train, X_test, y_train, y_test

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=0)
X_train.shape

### Making the model with X_train and y_train (no other parameters)

In [ ]:
linreg_model = LinearRegression()
linreg_model.fit(X_train,y_train)
linreg_model.coef_

In [ ]:
mean_squared_error(y_true=y_test,y_pred=linreg_model.predict(X_test))

105.54773116235636

In [ ]:
mean_absolute_error(y_true=y_test,y_pred=linreg_model.predict(X_test))

8.136907205766489

In [ ]:
max_error(y_true=y_test,y_pred=linreg_model.predict(X_test))

27.617983836869684

### Cross validation

In [ ]:
cv_10_folds = KFold(n_splits=10)
cross_val_score(linreg_model,X_train,y_train,cv=cv_10_folds).mean() #Mean of R²

0.5985788248508974

## Trying with X squares
Append X squares to X_train

In [ ]:
X_with_squares_train = np.append(X_train, np.array([x*x for x in X_train]),axis=1)
X_with_squares_test = np.append(X_test, np.array([x*x for x in X_test]), axis=1)
X_with_squares_train

array([[1.43000000e+02, 1.69400000e+02, 1.42700000e+02, ...,
        9.35862760e+05, 4.14092250e+05, 7.84000000e+02],
       [2.12000000e+02, 0.00000000e+00, 1.24780000e+02, ...,
        1.17809316e+06, 6.39264212e+05, 3.13600000e+03],
       [2.88000000e+02, 1.21000000e+02, 0.00000000e+00, ...,
        8.24464000e+05, 6.87241000e+05, 7.84000000e+02],
       ...,
       [1.44000000e+02, 0.00000000e+00, 1.75000000e+02, ...,
        8.89249000e+05, 7.12336000e+05, 7.84000000e+02],
       [2.39600000e+02, 3.59400000e+02, 0.00000000e+00, ...,
        8.86610560e+05, 4.41294490e+05, 7.84000000e+02],
       [1.92000000e+02, 2.88000000e+02, 0.00000000e+00, ...,
        8.64528040e+05, 5.12799210e+05, 8.10000000e+03]])

In [ ]:
linreg_model = LinearRegression()
linreg_model.fit(X_with_squares_train,y_train)
linreg_model.coef_

array([ 1.30789572e-01,  1.24655765e-01,  8.28374356e-02, -5.80829309e-01,
        1.07571030e+00, -1.21880451e-01,  2.62083386e-01,  3.51158972e-01,
       -2.99756130e-05, -1.38429332e-04, -2.26412089e-04,  1.17136480e-03,
       -4.36321327e-02,  6.86018536e-05, -1.63140574e-04, -7.97643965e-04])

In [ ]:
cross_val_score(linreg_model,X_with_squares_train,y_train,cv=cv_10_folds).mean()

0.7613655368106722

In [ ]:
mean_squared_error(y_test,y_pred=linreg_model.predict(X_with_squares_test))

In [ ]:
mean_absolute_error(y_test,y_pred=linreg_model.predict(X_with_squares_test))

In [ ]:
max_error(y_test,y_pred=linreg_model.predict(X_with_squares_test))

### Trying with cubes as well

In [284]:
X_with_cubes_and_squares_train = np.append(X_with_squares_train, np.array([x*x*x for x in X_train]),axis=1)
X_with_cubes_and_squares_test = np.append(X_with_squares_test, np.array([x*x*x for x in X_test]),axis=1)
linreg_model = LinearRegression()
linreg_model.fit(X_with_cubes_and_squares_train,y_train)
linreg_model.coef_

array([ 3.45273596e-01,  8.88548849e-02, -7.34983296e-02,  8.20336654e+00,
        1.47758856e+00,  2.40860236e+00,  2.16725562e+00,  6.30378017e-01,
       -7.50877438e-04,  1.80482698e-04,  1.75716696e-03, -4.84464145e-02,
       -1.26851186e-01, -2.52304983e-03, -2.68560606e-03, -3.70140059e-03,
        7.49122254e-07, -7.32975730e-07, -6.40773425e-06,  9.18778867e-05,
        2.33728554e-03,  8.79022019e-07,  1.10292030e-06,  6.07653690e-06])

In [285]:
cross_val_score(linreg_model,X_with_cubes_and_squares_train,y_train,cv=cv_10_folds).mean()

0.8253926984997244

In [286]:
mean_squared_error(y_true=y_test,y_pred=linreg_model.predict(X_with_cubes_and_squares_test))

44.51055836220856

In [287]:
mean_absolute_error(y_test,y_pred=linreg_model.predict(X_with_cubes_and_squares_test))

5.086468804779517

In [288]:
max_error(y_test,y_pred=linreg_model.predict(X_with_cubes_and_squares_test))

22.06278138102745

### Trying if root of features are pertinent

In [289]:
squares_with_root_train = np.array([x**(1/2) for x in X_with_squares_train])
X_with_squares_and_root_train = np.append(X_with_squares_train,squares_with_root_train,axis=1)

squares_with_root_test = np.array([x**(1/2) for x in X_with_squares_test])
X_with_squares_and_root_test = np.append(X_with_squares_test,squares_with_root_test,axis=1)

X_with_squares_and_root_train

array([[ 143.  ,  169.4 ,  142.7 , ...,  967.4 ,  643.5 ,   28.  ],
       [ 212.  ,    0.  ,  124.78, ..., 1085.4 ,  799.54,   56.  ],
       [ 288.  ,  121.  ,    0.  , ...,  908.  ,  829.  ,   28.  ],
       ...,
       [ 144.  ,    0.  ,  175.  , ...,  943.  ,  844.  ,   28.  ],
       [ 239.6 ,  359.4 ,    0.  , ...,  941.6 ,  664.3 ,   28.  ],
       [ 192.  ,  288.  ,    0.  , ...,  929.8 ,  716.1 ,   90.  ]])

In [290]:
linreg_model.fit(X_with_squares_and_root_train,y_train)
cross_val_score(linreg_model,X_with_squares_and_root_train,y_train,cv=cv_10_folds).mean()

0.8537593102120317

In [291]:
mean_squared_error(y_true=y_test,y_pred=linreg_model.predict(X_with_squares_and_root_test))

38.91794024322182

In [292]:
mean_absolute_error(y_test,y_pred=linreg_model.predict(X_with_squares_and_root_test))

5.025872748624753

In [293]:
max_error(y_test,y_pred=linreg_model.predict(X_with_squares_and_root_test))

17.989332975259998

In [294]:
X_all_train = np.append(X_with_cubes_and_squares_train, [x**(1/2) for x in X_train], axis=1)
X_all_test = np.append(X_with_cubes_and_squares_test, [x**(1/2) for x in X_test], axis=1)

linreg_model.fit(X_all_train,y_train)
linreg_model.coef_

array([ 3.29294114e+00,  2.27585817e-01, -1.46011783e+00, -2.55527908e+02,
        4.17187124e-01,  2.73627357e+02, -2.24746116e+01, -5.51521765e-01,
       -4.01875466e-03, -2.67892596e-04,  1.02039056e-02,  4.46189508e-01,
       -1.02143594e-01, -9.61573430e-02,  7.36015619e-03,  6.29143356e-04,
        2.77199863e-06, -4.31981700e-08, -2.73960067e-05, -4.56195638e-04,
        2.22872638e-03,  2.01836934e-05, -1.31719970e-06, -3.36618366e-07,
       -5.23931486e+01, -8.89407173e-01,  7.66575071e+00,  3.72793218e+03,
        1.96384459e+00, -8.97259613e+03,  7.48480013e+02,  9.51002700e+00])

In [295]:
cross_val_score(linreg_model, X_all_train, y_train).mean()

0.8668426907938922

In [296]:
mean_squared_error(y_true=y_test,y_pred=linreg_model.predict(X_all_test))

35.36081061873527

In [297]:
mean_absolute_error(y_test,y_pred=linreg_model.predict(X_all_test))

4.784151075004317

In [298]:
max_error(y_test,y_pred=linreg_model.predict(X_all_test))

18.4776370003552

In [299]:
#trying to add 1/x into the approximation function
X_final_train = np.append(X_all_train, np.array([x**-1 if x != 0 else np.Inf for x in X_all_train]), axis=1)
X_final_test = np.append(X_all_test, np.array([x**-1 if x != 0 else np.Inf for x in X_all_test]), axis=1)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

At this point, model with squares and square roots of features seems to be the best model

## Calculating MDL and AIC between the three linear regression models

### MDL and AIC for the base X_train features

In [301]:
from math import log

def mdl(xtrain, xtest):
    linreg_model.fit(xtrain,y_train)
    k = linreg_model.n_features_in_
    n = xtrain.shape[0]
    mse_ = mean_squared_error(y_true=y_test,y_pred=linreg_model.predict(xtest))
    return n*log(mse_)+k*log(n)

def aic(xtrain, xtest):
    linreg_model.fit(xtrain,y_train)
    k = linreg_model.n_features_in_
    n = xtrain.shape[0]
    mse_ = mean_squared_error(y_true=y_test,y_pred=linreg_model.predict(xtest))
    return n*log(mse_)+k*2

In [302]:
mdl_simple = mdl(X_train,X_test)
mdl_squares = mdl(X_with_squares_train, X_with_squares_test)
mdl_squares_and_cubes = mdl(X_with_cubes_and_squares_train, X_with_cubes_and_squares_test)
mdl_squares_and_root = mdl(X_with_squares_and_root_train, X_with_squares_and_root_test)
mdl_all = mdl(X_all_train, X_all_test)

[mdl_simple, mdl_squares, mdl_squares_and_cubes, mdl_squares_and_root, mdl_all]

[4373.699987861446,
 4054.399387764585,
 3682.6052839545337,
 3612.7916078644857,
 3523.9375724989104]

In [303]:
aic_simple = aic(X_train,X_test)
aic_squares = aic(X_with_squares_train, X_with_squares_test)
aic_squares_and_cubes = aic(X_with_cubes_and_squares_train, X_with_cubes_and_squares_test)
aic_squares_and_root = aic(X_with_squares_and_root_train, X_with_squares_and_root_test)
aic_all = aic(X_all_train, X_all_test)

[aic_simple, aic_squares, aic_squares_and_cubes, aic_squares_and_root, aic_all]

[4335.044359336919,
 3977.088130715531,
 3566.6383983809533,
 3458.1690937663784,
 3369.315058400803]

MDL and AIC are minimized for the square and root models