# Concrete quality analysis (Linear Regression)

### Importing modules

In [118]:
import numpy as np

from sklearn.model_selection import cross_val_score, train_test_split, KFold
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn import metrics

from pandas import read_excel

### Read file and convert as float array

In [119]:
df = read_excel("./Concrete_Data.xls",sheet_name="Sheet1",header=0,nrows=1030,dtype=float)
df

Cement (component 1)(kg in a m^3 mixture)   
0                                         540.0  \
1                                         540.0   
2                                         332.5   
3                                         332.5   
4                                         198.6   
...                                         ...   
1025                                      276.4   
1026                                      322.2   
1027                                      148.5   
1028                                      159.1   
1029                                      260.9   

      Blast Furnace Slag (component 2)(kg in a m^3 mixture)   
0                                                   0.0      \
1                                                   0.0       
2                                                 142.5       
3                                                 142.5       
4                                                 132.4       
...                                                 ...       
1025                                              116.0       
1026                                                0.0       
1027                                              139.4       
1028                                              186.7       
1029                                              100.5       

      Fly Ash (component 3)(kg in a m^3 mixture)   
0                                            0.0  \
1                                            0.0   
2                                            0.0   
3                                            0.0   
4                                            0.0   
...                                          ...   
1025                                        90.3   
1026                                       115.6   
1027                                       108.6   
1028                                         0.0   
1029                                        78.3   

      Water  (component 4)(kg in a m^3 mixture)   
0                                         162.0  \
1                                         162.0   
2                                         228.0   
3                                         228.0   
4                                         192.0   
...                                         ...   
1025                                      179.6   
1026                                      196.0   
1027                                      192.7   
1028                                      175.6   
1029                                      200.6   

      Superplasticizer (component 5)(kg in a m^3 mixture)   
0                                                   2.5    \
1                                                   2.5     
2                                                   0.0     
3                                                   0.0     
4                                                   0.0     
...                                                 ...     
1025                                                8.9     
1026                                               10.4     
1027                                                6.1     
1028                                               11.3     
1029                                                8.6     

      Coarse Aggregate  (component 6)(kg in a m^3 mixture)   
0                                                1040.0     \
1                                                1055.0      
2                                                 932.0      
3                                                 932.0      
4                                                 978.4      
...                                                 ...      
1025                                              870.1      
1026                                              817.9      
1027                                              892.4      
1028                                         

In [120]:
concrete_arr = df.to_numpy(float)
concrete_arr

array([[540.        ,   0.        ,   0.        , ..., 676.        ,
         28.        ,  79.98611076],
       [540.        ,   0.        ,   0.        , ..., 676.        ,
         28.        ,  61.88736576],
       [332.5       , 142.5       ,   0.        , ..., 594.        ,
        270.        ,  40.26953526],
       ...,
       [148.5       , 139.4       , 108.6       , ..., 780.        ,
         28.        ,  23.69660064],
       [159.1       , 186.7       ,   0.        , ..., 788.9       ,
         28.        ,  32.76803638],
       [260.9       , 100.5       ,  78.3       , ..., 761.5       ,
         28.        ,  32.40123514]])

### Split array in features and results:

In [121]:
X = concrete_arr[:,:-1]
y = concrete_arr[:,-1]
X.shape

(1030, 8)

### Add squared values of X to array

In [122]:
squares = np.array([x*x for x in X])

X_with_squares = np.append(X,squares,axis=1)
X_with_cubes_and_squares = np.append(X_with_squares,cubes,axis=1)
X_with_cubes_and_squares

array([[5.4000000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0816000e+06,
        4.5697600e+05, 7.8400000e+02],
       [5.4000000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.1130250e+06,
        4.5697600e+05, 7.8400000e+02],
       [3.3250000e+02, 1.4250000e+02, 0.0000000e+00, ..., 8.6862400e+05,
        3.5283600e+05, 7.2900000e+04],
       ...,
       [1.4850000e+02, 1.3940000e+02, 1.0860000e+02, ..., 7.9637776e+05,
        6.0840000e+05, 7.8400000e+02],
       [1.5910000e+02, 1.8670000e+02, 0.0000000e+00, ..., 9.7930816e+05,
        6.2236321e+05, 7.8400000e+02],
       [2.6090000e+02, 1.0050000e+02, 7.8300000e+01, ..., 7.4736025e+05,
        5.7988225e+05, 7.8400000e+02]])

### Split x and y into X_train, X_test, y_train, y_test

In [123]:
linreg_model = LinearRegression()
linreg_model.fit(X,y)
linreg_model.coef_

array([ 0.11978526,  0.10384725,  0.08794308, -0.1502979 ,  0.29068694,
        0.01803018,  0.02015446,  0.11422562])

### Model selection

In [124]:
cv = KFold(n_splits=10)
cross_val_score(linreg_model,X,y,cv=cv).mean() #Mean of R²

0.2780755819787789

### Trying with X squares

In [125]:
linreg_model = LinearRegression()
linreg_model.fit(X_with_squares,y)
linreg_model.coef_

array([ 1.27420305e-01,  1.22195754e-01,  8.73254608e-02, -6.41194600e-01,
        9.55781342e-01, -9.98483192e-02,  2.62928377e-01,  3.52160052e-01,
       -2.36155649e-05, -1.35960075e-04, -2.56008197e-04,  1.30356072e-03,
       -4.02192350e-02,  5.57426406e-05, -1.64833919e-04, -8.03475063e-04])

In [126]:
cross_val_score(linreg_model,X_with_squares,y,cv=cv).mean()

0.5564269205150838

### Trying with cubes as well

In [127]:
cubes = np.array([x*x for x in X])
X_with_cubes_and_squares = np.append(X_with_squares,cubes,axis=1)
linreg_model = LinearRegression()
linreg_model.fit(X_with_cubes_and_squares,y)
linreg_model.coef_

array([ 1.18181140e-01,  1.13140972e-01,  7.72408212e-02, -6.45977928e-01,
        1.09231160e+00, -1.00911775e-01,  2.55886973e-01,  3.53308503e-01,
        2.24310013e+06,  9.50287024e+06, -1.22268177e+06,  1.18603547e+05,
       -2.51295454e+03, -7.88621770e+09,  3.61295473e+09, -7.46936431e+07,
       -2.24310013e+06, -9.50287024e+06,  1.22268177e+06, -1.18603546e+05,
        2.51291392e+03,  7.88621770e+09, -3.61295473e+09,  7.46936431e+07])

In [128]:
cross_val_score(linreg_model,X_with_cubes_and_squares,y,cv=cv).mean()

0.5430573202951481

In [129]:
linreg_model = LinearRegression()
linreg_model.fit(X_with_squares,y)
mse = metrics.mean_squared_error(y,linreg_model.predict(X_with_squares))
mse

62.95349661595072

### Ploting

In [130]:
# import matplotlib.pyplot as plt